// Test entry point. Register every suite here.

runSmokeTests()
runTimeFormattingTests()
runPreferencesTests()
runTimerEngineTests()
runPomodoroConfigTests()
runMenuBarPresentationTests()
runStatsStoreTests()
runFocusBlockRulesTests()
runAllowlistRulesTests()
runDndRulesTests()
runPresenceRulesTests()
runActivityStoreTests()
runFocusLogTests()
runFocusClipTests()
runWeekRankingTests()
runHeatmapScaleTests()
runTimelineTicksTests()
runWeekRowHitTests()
runSitePromotionTests()
runUsageShareTests()
runTabSwitchPlanTests()
runHiddenAppsRecordTests()
runBlockEscalationTests()
finishTestRun()
