// Test entry point. Register every suite here.

runSmokeTests()
runTimeFormattingTests()
runPreferencesTests()
runTimerEngineTests()
runPomodoroConfigTests()
runMenuBarPresentationTests()
runStatsStoreTests()
runFocusBlockRulesTests()
runPresenceRulesTests()
runActivityStoreTests()
runFocusLogTests()
runWeekRankingTests()
runHeatmapScaleTests()
runTimelineTicksTests()
finishTestRun()
